export enum DB_TABLES {
  MODULES = "modules",
  AUDIT_TRAILS = "auditTrails",
  TRANSACTIONS = "transactions",
  GRAPH_METADATA = "graphMetadata",
  VELOCITY_SNAPSHOTS = "velocitySnapshots",
  FRAUD_ALERTS = "fraudAlerts",
  DEAD_LETTER_QUEUE = "deadLetterQueue",
  MODEL_METADATA = "modelMetadata",
  INVESTIGATION_REPORTS = "investigationReports",
  DECISION_AUDIT_LOG = "decisionAuditLog",
  API_KEYS = "apiKeys",
  WEBHOOK_SUBSCRIPTIONS = "webhookSubscriptions",
  WEBHOOK_DELIVERIES = "webhookDeliveries",
  MODEL_VERSIONS = "modelVersions",
  SEGMENT_THRESHOLDS = "segmentThresholds",
  RULES = "rules",
  IDEMPOTENCY_KEYS = "idempotencyKeys",
  INVESTIGATION_CONVERSATIONS = "investigationConversations",
}
